on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
name: deploy-waxz-cf-web-proxy

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@master
        with:
          repository: waxz/cf-web-proxy
          path: ./cf-web-proxy
          submodules: recursive
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "./cf-web-proxy"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy
