on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
name: deploy-waxz/cf-proxy-ex

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@master
        with:
          repository: waxz/cf-proxy-ex
          path: ./cf-proxy-ex
          submodules: recursive
      - name: Create wrangler configure file
        run: |
          cd ./cf-proxy-ex

          export WORKER_PROJECT_NAME="cf-proxy-ex"
          export WORKER_ENTRY="./_worker.js"
          export WORKER_COMPA_DATE="2025-04-27"

          cat << EOF | tee wrangler.toml
          # Top-level configuration
          name = "$WORKER_PROJECT_NAME"
          main = "$WORKER_ENTRY"
          compatibility_date = "$WORKER_COMPA_DATE"
          EOF

          # change password
          sed -i -e "s/.*const password = .*/const password = \"$CF_PROXY_PSW\";/"   $WORKER_ENTRY 
          # change ico
          sed -i -e "s#https://www.baidu.com/favicon.ico#https://github.com/favicon.ico#" $WORKER_ENTRY
          # change home page

          sed -i -e 's#const mainPage =.*#const mainPage = `<!DOCTYPE html><html><head><style>body{background:rgb(255, 255, 255);color:rgb(240,240,0);}a{color:rgb(250,250,180);}del{color:rgb(190,190,190);}.center{text-align:center;}.important{font-weight:bold;font-size:27;}/* my style begins*/form[id=urlForm] {max-width: 340px;min-width: 340px;margin: 0 auto;}input[id=targetUrl] {background-color: rgb(240,240,0);}button[id=jumpButton] {background-color: rgb(240,240,0);}</style></head><body></ul><form id="urlForm" onsubmit="redirectToProxy(event)"><fieldset><legend>Proxy Everything</legend><label for="targetUrl">TargetUrl: <input type="text" id="targetUrl" placeholder="Enter the target URL here..."></label><button type="submit" id="jumpButton">Jump!</button></fieldset></form><script>function redirectToProxy(event) {event.preventDefault();const targetUrl = document.getElementById("targetUrl").value.trim();const currentOrigin = window.location.origin;window.open(currentOrigin + "/" + targetUrl, "_blank");}</script><ul></body></html>`;\n \` #' $WORKER_ENTRY


        shell: bash
        env:
          CF_PROXY_PSW: ${{ secrets.CF_PROXY_PSW }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "./cf-proxy-ex"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            deploy